# Generated by Django 5.2.18 on 2026-10-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
