import django_filters

from .models import Product


class ProductFilter(django_filters.FilterSet):
    # ?category=keyboards  -> WHERE category.slug = 'keyboards' (JOIN generated by the ORM)
    category = django_filters.CharFilter(field_name="category__slug")
    min_price = django_filters.NumberFilter(field_name="price", lookup_expr="gte")
    max_price = django_filters.NumberFilter(field_name="price", lookup_expr="lte")

    class Meta:
        model = Product
        fields = ["category", "is_active", "min_price", "max_price"]
